
// 국적
export const countryList = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AS", name: "American Samoa" },
    { code: "AD", name: "Andorra" },
    { code: "AO", name: "Angola" },
    { code: "AI", name: "Anguilla" },
    { code: "AQ", name: "Antarctica" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "AR", name: "Argentina" },
    { code: "AM", name: "Armenia" },
    { code: "AW", name: "Aruba" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbados" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Benin" },
    { code: "BM", name: "Bermuda" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BA", name: "Bosnia and Herzegovina" },
    { code: "BW", name: "Botswana" },
    { code: "BR", name: "Brazil" },
    { code: "IO", name: "British Indian Ocean Territory" },
    { code: "BN", name: "Brunei Darussalam" },
    { code: "BG", name: "Bulgaria" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CA", name: "Canada" },
    { code: "CV", name: "Cape Verde" },
    { code: "KY", name: "Cayman Islands" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CX", name: "Christmas Island" },
    { code: "CC", name: "Cocos (Keeling) Islands" },
    { code: "CO", name: "Colombia" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "CD", name: "Congo, Democratic Republic of the" },
    { code: "CK", name: "Cook Islands" },
    { code: "CR", name: "Costa Rica" },
    { code: "CI", name: "Cote D'Ivoire" },
    { code: "HR", name: "Croatia" },
    { code: "CU", name: "Cuba" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DK", name: "Denmark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "EC", name: "Ecuador" },
    { code: "EG", name: "Egypt" },
    { code: "SV", name: "El Salvador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "EE", name: "Estonia" },
    { code: "ET", name: "Ethiopia" },
    { code: "FK", name: "Falkland Islands (Malvinas)" },
    { code: "FO", name: "Faroe Islands" },
    { code: "FJ", name: "Fiji" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "GF", name: "French Guiana" },
    { code: "PF", name: "French Polynesia" },
    { code: "TF", name: "French Southern Territories" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GE", name: "Georgia" },
    { code: "DE", name: "Germany" },
    { code: "GH", name: "Ghana" },
    { code: "GI", name: "Gibraltar" },
    { code: "GR", name: "Greece" },
    { code: "GL", name: "Greenland" },
    { code: "GD", name: "Grenada" },
    { code: "GP", name: "Guadeloupe" },
    { code: "GU", name: "Guam" },
    { code: "GT", name: "Guatemala" },
    { code: "GG", name: "Guernsey" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "HM", name: "Heard Island & Mcdonald Islands" },
    { code: "VA", name: "Vatican City State (Holy See)" },
    { code: "HN", name: "Honduras" },
    { code: "HK", name: "Hong Kong" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran, Islamic Republic of" },
    { code: "IQ", name: "Iraq" },
    { code: "IE", name: "Ireland" },
    { code: "IM", name: "Isle of Man" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "JM", name: "Jamaica" },
    { code: "JP", name: "Japan" },
    { code: "JE", name: "Jersey" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KR", name: "South Korea" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Lao People's Democratic Republic" },
    { code: "LV", name: "Latvia" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libyan Arab Jamahiriya" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MO", name: "Macao" },
    { code: "MK", name: "North Macedonia" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malta" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MQ", name: "Martinique" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "YT", name: "Mayotte" },
    { code: "MX", name: "Mexico" },
    { code: "FM", name: "Micronesia, Federated States of" },
    { code: "MD", name: "Moldova, Republic of" },
    { code: "MC", name: "Monaco" },
    { code: "MN", name: "Mongolia" },
    { code: "ME", name: "Montenegro" },
    { code: "MS", name: "Montserrat" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "MM", name: "Myanmar" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NL", name: "Netherlands" },
    { code: "NC", name: "New Caledonia" },
    { code: "NZ", name: "New Zealand" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "NU", name: "Niue" },
    { code: "NF", name: "Norfolk Island" },
    { code: "MP", name: "Northern Mariana Islands" },
    { code: "NO", name: "Norway" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palau" },
    { code: "PS", name: "Palestinian Territory, Occupied" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PN", name: "Pitcairn" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "PR", name: "Puerto Rico" },
    { code: "QA", name: "Qatar" },
    { code: "RE", name: "Reunion" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russian Federation" },
    { code: "RW", name: "Rwanda" },
    { code: "BL", name: "Saint Barthelemy" },
    { code: "SH", name: "Saint Helena" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "LC", name: "Saint Lucia" },
    { code: "MF", name: "Saint Martin" },
    { code: "PM", name: "Saint Pierre and Miquelon" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "Sao Tome and Principe" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SN", name: "Senegal" },
    { code: "RS", name: "Serbia" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapore" },
    { code: "SX", name: "Sint Maarten" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "SB", name: "Solomon Islands" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    { code: "GS", name: "South Georgia and the South Sandwich Islands" },
    { code: "SS", name: "South Sudan" },
    { code: "ES", name: "Spain" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SJ", name: "Svalbard and Jan Mayen" },
    { code: "SZ", name: "Swaziland" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "SY", name: "Syrian Arab Republic" },
    { code: "TW", name: "Taiwan, Province of China" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania, United Republic of" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TG", name: "Togo" },
    { code: "TK", name: "Tokelau" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TR", name: "Turkey" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TC", name: "Turks and Caicos Islands" },
    { code: "TV", name: "Tuvalu" },
    { code: "UG", name: "Uganda" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "UM", name: "United States Minor Outlying Islands" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VU", name: "Vanuatu" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "VG", name: "Virgin Islands, British" },
    { code: "VI", name: "Virgin Islands, U.S." },
    { code: "WF", name: "Wallis and Futuna" },
    { code: "EH", name: "Western Sahara" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" },
];



// 전공
// components/SelectList.js 등에서 관리
export const majorList = [
    { value: 'Film Studies', label: '영화과 (Film Studies)' },
    { value: 'Music & Entertainment', label: '뮤지컬엔터테인먼트학과 (Music & Entertainment)' },
    { value: 'Acting', label: '연기과 (Acting)' },
    { value: 'Design Studies', label: '디자인학부 (Design Studies)' },
    { value: 'Architecture', label: '건축학과 (Architecture)' },
    { value: 'Fashion Design', label: '패션디자인학과 (Fashion Design)' },
    { value: 'Advertising & Public Relations', label: '광고홍보학과 (Advertising & PR)' },
    { value: 'Broadcasting & Video', label: '방송영상학과 (Broadcasting & Video)' },
    { value: 'Game Studies', label: '게임학과 (Game Studies)' },
    { value: 'Animation', label: '영상애니메이션학과 (Animation)' },
    { value: 'Webtoon', label: '웹툰학과 (Webtoon)' },
    { value: 'Digital Finance', label: '디지털금융학과 (Digital Finance)' },
    { value: 'Computer Science', label: '컴퓨터공학과 (Computer Science)' },
    { value: 'Software Engineering', label: '소프트웨어학과 (Software Engineering)' },
    { value: 'Information Security', label: '정보보안학과 (Information Security)' },
    { value: 'Electrical Engineering', label: '전기전자공학과 (Electrical Engineering)' },
    { value: 'Mechanical Engineering', label: '기계공학과 (Mechanical Engineering)' },
    { value: 'Architectural Engineering', label: '건축공학과 (Architectural Engineering)' },
    { value: 'Civil Engineering', label: '토목공학과 (Civil Engineering)' },
    { value: 'Business Administration', label: '경영학전공 (Business Administration)' },
    { value: 'Accounting', label: '회계세무학전공 (Accounting)' },
    { value: 'International Trade', label: '국제통상학과 (International Trade)' },
    { value: 'International Studies', label: '국제물류학과 (International Studies)' },
    { value: 'English Language & Literature', label: '영어학과 (English Language & Literature)' },
    { value: 'Japanese Language', label: '일본어학과 (Japanese Language)' },
    { value: 'Chinese Language', label: '중국어학과 (Chinese Language)' },
    { value: 'Hotel Management', label: '호텔경영학과 (Hotel Management)' },
    { value: 'Asia Studies', label: '캠퍼스아시아학과 (Asia Studies)' },
    { value: 'Healthcare Administration', label: '보건행정학과 (Healthcare Administration)' },
    { value: 'Dental Hygiene', label: '치위생학과 (Dental Hygiene)' },
    { value: 'Sports Science', label: '운동처방학과 (Sports Science)' },
    { value: 'Cosmetic Science', label: '화장품학과 (Cosmetic Science)' },
    { value: 'Clinical Pathology', label: '임상병리학과 (Clinical Pathology)' },
    { value: 'Nursing', label: '간호학과 (Nursing)' },
    { value: 'Radiological Science', label: '방사선학과 (Radiological Science)' },
    { value: 'Occupational Therapy', label: '작업치료학과 (Occupational Therapy)' },
    { value: 'Food & Nutrition', label: '식품영양학과 (Food & Nutrition)' },
    { value: 'Social Welfare', label: '사회복지학과 (Social Welfare)' },
    { value: 'Youth Counseling & Psychology', label: '청소년상담심리학과 (Youth Counseling & Psychology)' },
    { value: 'Police Science', label: '경찰학과 (Police Science)' },
    // 필요시 계속 추가 가능
    { value: 'Other', label: '기타 (Other)' }
];



// 언어
export const languageList = [
    { value: "Korean", label: "한국어 (Korean)" },
    { value: "English", label: "영어 (English)" },
    { value: "Japanese", label: "일본어 (Japanese)" },
    { value: "Chinese", label: "중국어 (Chinese)" },
    { value: "Spanish", label: "스페인어 (Spanish)" },
    { value: "French", label: "프랑스어 (French)" },
    { value: "German", label: "독일어 (German)" },
    { value: "Russian", label: "러시아어 (Russian)" },
    { value: "Vietnamese", label: "베트남어 (Vietnamese)" },
    { value: "Thai", label: "태국어 (Thai)" },
    { value: "Indonesian", label: "인도네시아어 (Indonesian)" },
    { value: "Mongolian", label: "몽골어 (Mongolian)" },
    { value: "Arabic", label: "아랍어 (Arabic)" },
    { value: "Portuguese", label: "포르투갈어 (Portuguese)" },
    { value: "Hindi", label: "힌디어 (Hindi)" },
    { value: "Italian", label: "이탈리아어 (Italian)" },
    { value: "Malay", label: "말레이어 (Malay)" },
    { value: "Burmese", label: "버마어 (Burmese)" },
    { value: "Uzbek", label: "우즈베크어 (Uzbek)" },
    { value: "Turkish", label: "터키어 (Turkish)" },
    { value: "Other", label: "기타 (Other)" }
];


// 종교
export const religionList = [
    { value: "None", label: "무종교 (None)" },
    { value: "Christian", label: "기독교 (Christian)" },
    { value: "Catholic", label: "천주교 (Catholic)" },
    { value: "Buddhist", label: "불교 (Buddhist)" },
    { value: "Muslim", label: "이슬람 (Muslim)" },
    { value: "Hindu", label: "힌두교 (Hindu)" },
    { value: "Jewish", label: "유대교 (Jewish)" },
    { value: "Sikh", label: "시크교 (Sikh)" },
    { value: "Confucian", label: "유교 (Confucian)" },
    { value: "Shinto", label: "신토 (Shinto)" },
    { value: "Other", label: "기타 (Other)" }
];


// 식습관
export const dietList = [
    { value: "None", label: "해당 없음 (None)" },
    { value: "Vegetarian", label: "채식주의 (Vegetarian)" },
    { value: "Vegan", label: "비건 (Vegan)" },
    { value: "Halal", label: "할랄 (Halal)" },
    { value: "Kosher", label: "코셔 (Kosher)" },
    { value: "Gluten-free", label: "글루텐 프리 (Gluten-free)" },
    { value: "Pescatarian", label: "페스코 채식 (Pescatarian)" },
    { value: "Lacto-vegetarian", label: "락토 채식 (Lacto-vegetarian)" },
    { value: "Ovo-vegetarian", label: "오보 채식 (Ovo-vegetarian)" },
    { value: "Likes spicy food", label: "매운 음식 선호 (Likes spicy food)" },
    { value: "Other", label: "기타 (Other)" }
];


// 취미
export const hobbyList = [
    { value: "Soccer", label: "축구 (Soccer)" },
    { value: "Basketball", label: "농구 (Basketball)" },
    { value: "Baseball", label: "야구 (Baseball)" },
    { value: "Volleyball", label: "배구 (Volleyball)" },
    { value: "Tennis", label: "테니스 (Tennis)" },
    { value: "Badminton", label: "배드민턴 (Badminton)" },
    { value: "Swimming", label: "수영 (Swimming)" },
    { value: "Running", label: "러닝 (Running)" },
    { value: "Cycling", label: "자전거 (Cycling)" },
    { value: "Table Tennis", label: "탁구 (Table Tennis)" },
    { value: "Dancing", label: "댄스 (Dancing)" },
    { value: "Singing", label: "노래 (Singing)" },
    { value: "Music", label: "음악 감상 (Music)" },
    { value: "Reading", label: "독서 (Reading)" },
    { value: "Traveling", label: "여행 (Traveling)" },
    { value: "Photography", label: "사진 (Photography)" },
    { value: "Cooking", label: "요리 (Cooking)" },
    { value: "Watching Movies", label: "영화 감상 (Watching Movies)" },
    { value: "Art", label: "미술/그림 (Art)" },
    { value: "Gaming", label: "게임 (Gaming)" },
    { value: "Board Games", label: "보드게임 (Board Games)" },
    { value: "Hiking", label: "등산 (Hiking)" },
    { value: "Yoga", label: "요가 (Yoga)" },
    { value: "Other", label: "기타 (Other)" }
];
